services:
  # PostgreSQL with pgvector extension
  db:
    image: ankane/pgvector:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: rag_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  # Permit.io PDP (Policy Decision Point)
  pdp:
    image: permitio/pdp-v2:latest
    environment:
      PDP_API_KEY: ${PERMIT_API_KEY}
      PDP_DEBUG: "true"
    ports:
      - "7766:7000"
    depends_on:
      - db
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:7000/health"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Our RAG application
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: postgresql://postgres:postgres@db:5432/rag_db
      PERMIT_API_KEY: ${PERMIT_API_KEY}
      PERMIT_PDP_URL: http://pdp:7000
      OPENAI_API_KEY: ${OPENAI_API_KEY}
    volumes:
      - ./src:/app/src
    depends_on:
      db:
        condition: service_healthy
      pdp:
        condition: service_healthy

volumes:
  postgres_data: